In [15]:
!pip install BeautifulSoup4

Requirement already satisfied: BeautifulSoup4 in /home/souvic/.conda/envs/py38/lib/python3.8/site-packages (4.10.0)
Requirement already satisfied: soupsieve>1.2 in /home/souvic/.conda/envs/py38/lib/python3.8/site-packages (from BeautifulSoup4) (2.2.1)

In [16]:
import pickle
import pandas as pd
from bs4 import BeautifulSoup

In [17]:
# path
AIEEE = '../../../jalend/aieeedata/'
AIEEE_2004 = AIEEE+'2004.p'
AIEEE_2005 = AIEEE+'2005.p'
AIEEE_2006 = AIEEE+'2006.p'
AIEEE_2007 = AIEEE+'2007.p'
AIEEE_2008 = AIEEE+'2008.p'

In [18]:
with (open(AIEEE_2006, "rb")) as openfile:
    ai_09 = pickle.load(openfile)

In [19]:
rolls = ai_09.keys()

In [20]:
rn = []
for key in rolls:
    rn.append(key)

In [21]:
# Paper 1: Physics, Chemistry &amp; Mathematics
# Paper 2: Mathematics, Aptitude Test &amp; Drawing

In [35]:
data = []
count = 0
for elem in rn:
    student = []
    count = count+1
    if count%10000 == 0:
        print(count)
        df = pd.DataFrame(data, columns=['roll_no','name','mother_name','father_name','present','state','p1_marks','p2_marks','air_btech','state_btech','air_barch','state_barch'])
    if ai_09[elem] == "":
        continue
    soup = BeautifulSoup(ai_09[elem],'html.parser')
    tab  = soup.find_all('table', align="center", border="0", width="500")
    info0 = tab[0].find_all('td', align="left")
    roll_no = info0[0].string
    name = info0[1].string
    mother_name = info0[2].string
    father_name = info0[3].string
    student= student+([roll_no, name, mother_name, father_name])
    taba = soup.find_all('table',width='400')
    if len(tab) <= 2:
        present = False
        student.append(present)
#         print(taba[0].text,":",elem)
    else :
        present = True
        info2 = tab[1].find_all('td', align='right')
        p1_marks = info2[1].string
        p2_marks = info2[2].string
        try:
            state = tab[2].find_all('td')[-3].text
        except:
            import pdb; pdb.set_trace()
        info = tab[2].find_all('td', align='center')
        air_btech = info[2].text
        state_btech = info[4].text
        air_barch = info[3].text
        state_barch = info[5].text
        student=student+([state, present, p1_marks, p2_marks, air_btech, state_btech, air_barch, state_barch])
#     import pdb; pdb.set_trace()
    data.append(student)

10000
20000
30000
40000
50000

In [36]:
df = pd.DataFrame(data, columns=['roll_no','name','mother_name','father_name','state','present','p1_marks','p2_marks','air_btech','state_btech','air_barch','state_barch'])

In [40]:
%mkdir new_data

In [41]:
df.to_csv('new_data/aieee_2006.csv')

In [43]:
df.head(40)

,roll_no,name,mother_name,father_name,state,present,p1_marks,p2_marks,air_btech,state_btech,air_barch,state_barch
0,27400413,SAGAR PHUTELA,MEERA PHUTELA,RAVINDAR PHUTELA,Uttaranchal\r\n\t(State code of eligibility/S...,True,46.50,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,219848,5692,------,------
1,23307553,SHOBHAN MINZ,MANILA MINZ,BISHRAM MINZ,State Rank\n( State code of eligibility : 16 ),True,27.00,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,304668,14837,------,------
2,27801315,NAVNEET KUMAR,SANDHYA GUPTA,KISHOR KUMAR GUPTA,State Rank\n( State code of eligibility : 33 ),True,22.00,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,327239,54415,------,------
3,21657062,KRISHNA MURARI KARNA,PRAMILA DEVI,MAHESH KUMAR KARNA,False,None,None,None,None,None,None,None
4,20602570,K CH SANDILYA BALIVADA,SUGUNA BALIVADA,RANGA RAO BT,State Rank\n( State code of eligibility : 02 ),True,3.50,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,412817,36599,------,------
5,23410992,AKASH PRADHAN,TAPASWINI PRADHAN,DEVENDRA PRADHAN,False,None,None,None,None,None,None,None
6,23003529,MUKUND MADHAV,SUCHITA DEVI,SHIV SHANKAR KAPRI,State Rank\n( State code of eligibility : 16 ),True,-13.50,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,461912,23139,------,------
7,28510463,SOURATH MONDAL,RUBI MONDAL,CHITTA RANJAN MONDAL,State Rank\n( State code of eligibility : 35 ),True,25.00,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,312876,11534,------,------
8,24606238,THAKARE UMESH MADHUKARRAO,PUSHPA M THAKARE,MADHUKARRAO M THAKARE,State Rank\n( State code of eligibility : 21 ),True,63.50,\r\n\r\n 52.50\r\n\r\n,165617,8395,58803,3942
9,21637976,ASHISH KUMAR RANJAN,LATE CHANDRAWATI SINHA,SATYADEV PRASAD,State Rank\n( State code of eligibility : 05 ),True,55.50,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,189676,14807,------,------
10,26400292,DIVYANSHU BANSAL,INDU BANSAL,OM PRAKASH BANSAL,State Rank\n( State code of eligibility : 29 ),True,276.00,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,5744 *,1090,------,------
11,24800133,KULKARNI OMKAR VIJAYKUMAR,KULKARNI MANASI VIJAYKUMAR,KULKARNI VIJAYKUMAR SHRIPATI,State Rank\n( State code of eligibility : 21 ),True,80.00,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,126850,5944,------,------
12,22303157,SAHOO DEEPANWITA ARUN KUMAR,TAPASI SAHOO,AKUN KUMAR SAHOO,State Rank\n( State code of eligibility : 13 ),True,-7.50,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,448475,18935,------,------
13,26615461,B VINODHINI,B JAYARANI,G BABU,State Rank\n( State code of eligibility : 31 ),True,39.50,\r\n\r\n 93.00\r\n\r\n,248106,13289,37719 +,1444
14,24000931,ANIL MANUEL NETTO,BLAIZY JOSEPH,JOSEPH DIAGO NETTO,State Rank\n( State code of eligibility : 18 ),True,62.50,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,169472,7760,------,------
15,20905636,JYOTI CHETRI,KHARGAMAYA CHETRI,KARNA SINGH CHETRI,State Rank\n( State code of eligibility : 04 ),True,34.50,\r\n\r\n 104.50\r\n\r\n,269988,3124,31342,754
16,20800223,TAKUT NUNGNU,YAW NUNGNU,TAGIA NUNGNU,State Rank\n( State code of eligibility : 03 ),True,-12.00,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,459255,820,------,------
17,20200922,SUDHA MAHENDRA NATH REDDY,SUDHA LAKSHMI DEVI,SUDHA MAHESWARA REDDY,State Rank\n( State code of eligibility : 02 ),True,13.50,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,369120,34007,------,------
18,22600686,SUNNY MOHAMMAD,LATA DEVI,FAZAL DEEN,State Rank\n( State code of eligibility : 14 ),True,-20.50,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,472973,5256,------,------
19,21635363,RAJIT NARANG,SUSHMA NARANG,ASHOK KUMAR NARANG,State Rank\n( State code of eligibility : 10 ),True,38.00,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,253996,18360,------,------
20,27103216,GAJENDRA SINGH,JANKI SINGH,MADAN MOHAN SINGH,Uttaranchal\r\n\t(State code of eligibility/S...,True,62.50,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,168844,4270,------,------
21,24500927,ANIL GAYARI,VARDIBAI GAYARI,BHERULAL DHANGAR,State Rank\n( State code of eligibility : 20 ),True,-2.50,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,435040,26249,------,------
22,22801135,AZHAR AMIN ZARGAR,RAHILA BEGAM,MOHD AMIN ZARGAR,State Rank\n( State code of eligibility : 15 ),True,76.50,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,134918 #,736,------,------
23,24201543,SHILPA JETHANI,DEEPIKA JETHANI,N K JETHANI,State Rank\n( State code of eligibility : 20 ),True,1.50,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,419092,24911,------,------
24,20202882,KANIGIRI MANI KRISHNA,KANIGIRI PUSPHAVATI,KANIGIRI VISWANATHAM,State Rank\n( State code of eligibility : 02 ),True,38.00,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,254697,26155,------,------
25,28003873,VIKAS CHAUDHARY,MALTI CHAUDHARY,RAM SAJEEVAN CHAUDHARY,State Rank\n( State code of eligibility : 33 ),True,20.50,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,333866,55405,------,------
26,24712562,SHRUTI SAXENA,ABHA SAXENA,SUNIL GYANCHANDRA SAXENA,State Rank\n( State code of eligibility : 21 ),True,53.50,\r\n\r\n ABS\r\n\r\n,195384,10436,------,------
27,21647090,HARSHIT CHOPRA,KIRAN CHOPRA,MADAN MOHAN CHOPRA,State Rank\n( State code of eligibility : 10 ),True,31.50,\r\n\r\n 73.00\r\n\r\n,282613,19983,48275,4278
28,28303547,ADITYA VIJAY,RAJKUMARI,ARUN KUMAR,State Rank\n( State code of eligibility : 05 ),True,-5.00,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,442225,38451,------,------
29,26109326,SAKET SINGH CHAUDHARY,RAJWATI DEVI,RAMVEER SINGH CHAUDHARY,State Rank\n( State code of eligibility : 29 ),True,22.50,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,326038,18558,------,------
30,25802121,RONALD SINGH,GURMEET KAUR,S IQBALJIT SINGH,State Rank\n( State code of eligibility : 28 ),True,144.50,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,48222 #,989,------,------
31,24900026,RAJKUMARI BIDYALAKSHMI DEVI,RAJKUMARI ONGBI N SANAREI DEVI,RAJKUMAR BUDHI SINGH,State Rank\n( State code of eligibility : 22 ),True,-34.50,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,485034,1254,------,------
32,21600262,SWATI BHUTANI,SUSHMA BHUTANI,HARI KRISHAN BHUTANI,State Rank\n( State code of eligibility : 10 ),True,60.50,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,174989,13471,------,------
33,26610940,ABHILASH A,KALYANI ANAND,ANAND KUMAR,State Rank\n( State code of eligibility : 31 ),True,9.50,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,385346,21544,------,------
34,22400187,PRIYANKA JUNEJA,KIRAN JUNEJA,VED PARKASH JUNEJA,State Rank\n( State code of eligibility : 13 ),True,29.50,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,292842,11480,------,------
35,21658544,SAHEB HUSEN ANSARI,NASIRA,HANIF ANSARI,State Rank\n( State code of eligibility : 05 ),True,1.50,\r\n\r\n 1.50\r\n\r\n,419179,35955,72303,5997
36,24509135,DURGESH PATIDAR,NADU PATIDAR,DAYARAM PATIDAR,State Rank\n( State code of eligibility : 20 ),True,97.50,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,96555,4640,------,------
37,22203391,RAMANDEEP KAUR,AMARJIT KAUR,NACHHATAR SINGH,State Rank\n( State code of eligibility : 13 ),True,60.50,\r\n\r\n 56.00\r\n\r\n,175049,6324,57182,1904
38,26000511,ANKUSH KHANDELWAL,KANTA KHANDELWAL,R L KHANDELWAL,State Rank\n( State code of eligibility : 29 ),True,352.00,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,1039 *,239,------,------
39,27804972,SAROJ KUMAR ROY,YASODA DEVI,RAJESWAR ROY,State Rank\n( State code of eligibility : 05 ),True,-5.50,\r\n\r\nNot Applicable/Not Applied\r\n\r\n,443605,38610,------,------

Add labels

In [44]:
import os
os.environ["CUDA_VISIBLE_DEVICES"]="-1"    
import tensorflow as tf

In [45]:
def vocab():
    alpha = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
    special = [' ']
    vocab = alpha+special+['END']

    return vocab
    
def getIndex(df, maxlen, file):
    voc = vocab()
    char_index = dict((c, i) for i, c in enumerate(voc))
    
    X = []
    next_name = False
    
    # Club all the whitespaces
    
    trunc_X = [str(i).lower()[0:maxlen] for i in df['name']]
    mask = []
    for i in range(len(trunc_X)):
        name = trunc_X[i]
        tmp = []
        for char in str(name):
            if char not in voc:
                with open(file,'a') as f:
                    f.write(name+'\n')
                print(name)
                next_name = True
                break
            else:
                tmp.append(char_index[char])
        if next_name:
            mask.append(False)
            next_name = False
            continue
        mask.append(True)
        for k in range(0,maxlen - len(str(name))):
            tmp.append(char_index["END"])
        X.append(tmp)
            
    return np.asarray(X), df[mask]

In [46]:
import re
import numpy as np

def preprocess_df(df):
    df['name'] = [str(name).lower() for name in df['name']]
    df['name'] = [str(name).strip() for name in df['name']]
    df['name'] = [re.sub('[^a-zA-Z]+', ' ', str(name)) for name in df['name']]
    df['name'] = [re.sub('[ \t\n]+',' ', str(name)) for name in df['name']]
    df['name'].replace('', np.nan, inplace=True)
    df = df[df['name']!='nan']
    df.dropna(subset=['name'],inplace=True)
    return df

In [47]:
def returnGenderPred(df, model):
    test_x, df = getIndex(df, 30, 'oov.txt')
    pred = model.predict(np.asarray(test_x), verbose = 1)
    y_pred = np.argmax(pred, axis =1)
    df['Gender'] = y_pred
    return df

def returnCastePred(df, model):
    df = preprocess_df(df)
    test_x, df = getIndex(df, 30, 'oov.txt')
    pred = model.predict(np.asarray(test_x), verbose = 1)
    y_pred = np.argmax(pred, axis =1)
    df['Caste'] = y_pred
    return df

In [48]:
from keras.models import load_model


def get_gender_model():
    filename = "/home/souvic/mounted/btp/vahini/Models/ERTrain/SavedModels/FinalSet/CharLSTM/ERModel/ERModel"
    model = load_model(filename)
    return model

def get_caste_model():
    filename = "/home/souvic/mounted/btp/vahini/Name2Demographics/Models/AIEEEData/CNNModel/SavedModel/CasteModel"
    model = load_model(filename)
    return model

In [49]:
gender_model = get_gender_model()
caste_model = get_caste_model()

WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.

2022-02-14 23:14:03.389170: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-02-14 23:14:03.389310: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: obelix
2022-02-14 23:14:03.389334: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: obelix
2022-02-14 23:14:03.389556: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 470.86.0
2022-02-14 23:14:03.389635: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 470.86.0
2022-02-14 23:14:03.389663: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 470.86.0
2022-02-14 23:14:03.390423: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [50]:
df = pd.read_csv("new_data/aieee_2006.csv")
df = preprocess_df(df)
df = returnGenderPred(df, gender_model)
df = returnCastePred(df, caste_model)
del df['Unnamed: 0']
df.to_csv("new_data/aieee_2006.csv")

1810/1810 [==============================] - 588s 324ms/step
1810/1810 [==============================] - 14s 7ms/step